### ISSUE TITLE
Help text for TextBuffer.get_end_iter() is incorrect

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/docs#1]
Looks like it's the help text for something else.

Also, I'm not certain if this is the right repo to file this issue against, so hopefully it is!

**Comment by gkoz** [comment]
It's in the https://github.com/gtk-rs/lgpl-docs repo. Can't link to the specific line because the `gtk/vendor.md` file is too big. Most of vendor (not adapted for Rust) docs can be more or less confusing.
